# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfac5dc084c3f29830733414b974ea02d751d8c929f991e46ab00987b490dfe8f791fdd70542e75ff7d8ad15802c3554398c71512e4d3e39b8fe4371bf08eb2f

test:
  secret_key_base: 90a6947cf61a1e2d3f74440d46657506bb422dbac98c043a274e4f7850f11b3e4bff35c83300d01304340507e784192e5cac2c9aefd6545d1f351021127561e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
